kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "jmeter-oradb-output"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard